<?php
/*
This Files containg the  femqueen.com site  information

*/
$SITE_SETTINGS= array();

$SITE_SETTINGS['SITE_TITLE']='femqueen';
$SITE_SETTINGS['SITE_SLOGAN']='Connection women';
$SITE_SETTINGS['SITE_STATUS']=0;
$SITE_SETTINGS['OFFLINE_MESSAGE']='Updation is going on...we will run this system very soon';
$SITE_SETTINGS['SITE_ADMIN_MAIL']='dharma_inin@yahoo.co.in';
$SITE_SETTINGS['PAYMENT_SETTINGS']='';
$SITE_SETTINGS['LANGUAGE_CODE']='english';
$SITE_SETTINGS['BASE_URL']='';
$SITE_SETTINGS['UPLOAD_LIMIT']='';
$SITE_SETTINGS['HOSTNAME']='femqueen.com';
$SITE_SETTINGS['TWITTER_USERNAME']='';
$SITE_SETTINGS['TWITTER_PASSWORD']='';
$SITE_SETTINGS['PRIVATE_PROJECT_AMOUNT']='';
$SITE_SETTINGS['JOBLISTING_PROJECT_AMOUNT']='';
$SITE_SETTINGS['FORCED_ESCROW']='';
$SITE_SETTINGS['FEATURED_PROJECT_AMOUNT_CM']='';
$SITE_SETTINGS['URGENT_PROJECT_AMOUNT_CM']='';
$SITE_SETTINGS['PRIVATE_PROJECT_AMOUNT_CM']='';
$SITE_SETTINGS['JOBLIST_VALIDITY_LIMIT']='';
$SITE_SETTINGS['GOOGLE_AD_SENSE']='';
$SITE_SETTINGS['SITE_LOGO']='';
$SITE_SETTINGS['META_TAGS']='';
$SITE_SETTINGS['META_TAGS_DESCRIPTION']='';
$SITE_SETTINGS['DEFAULT_LANGUAGE']='';
$SITE_SETTINGS['DEAL_DEFAULT_CATECORY']='';
$SITE_SETTINGS['PRODUCT_NAME']='';
$SITE_SETTINGS['PRODUCT_VERSION']='';
$SITE_SETTINGS['PRODUCT_MODE']='';
$SITE_SETTINGS['DI_LICENSE_KEY']='';
$SITE_SETTINGS['DI_LICENSE_LOCAL_KEY']='';

?>